name: 'ad_reporting'
version: '0.7.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: ar_adspend

vars:
  api_source: google_ads
  ad_reporting__pinterest_enabled: false
  ad_reporting__microsoft_ads_enabled: false
  ad_reporting__linkedin_ads_enabled: false
  ad_reporting__google_ads_enabled: true
  ad_reporting__twitter_ads_enabled: false
  ad_reporting__facebook_ads_enabled: true
  ad_reporting__snapchat_ads_enabled: false
  ad_reporting__tiktok_ads_enabled: false

models:
  ad_reporting:
    +materialized: view
  
  pinterest:
    enabled: false
  pinterest_source:
    enabled: false
  
  microsoft_ads:
    enabled: false
  microsoft_ads_source:
    enabled: false
  
  linkedin:
    enabled: false
  linkedin_source:
    enabled: false
  
  twitter_ads:
    enabled: false
  twitter_ads_source:
    enabled: false
  
  snapchat_ads:
    enabled: false
  snapchat_ads_source:
    enabled: false

  tiktok_ads:
    enabled: false
  tiktok_ads_source:
    enabled: false
