version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9-stretch

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run:
          name: "Setup dbt"
          command: |
            sudo apt install libsasl2-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install -r integration_tests/requirements.txt
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml
      - run:
          name: "Run Tests - Spark (final_url)"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target spark --full-refresh
            dbt run --target spark --full-refresh
            dbt test --target spark
      - run:
          name: "Run Tests - Redshift (final_url)"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target redshift --full-refresh
            dbt run --target redshift --full-refresh
            dbt test --target redshift
      - run:
          name: "Run Tests - Snowflake (final_url)"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target snowflake --full-refresh
            dbt run --target snowflake --full-refresh
            dbt test --target snowflake
      - run:
          name: "Run Tests - BigQuery (final_url)"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/home/circleci/gcloud-service-key.json"

          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target bigquery --full-refresh
            dbt run --target bigquery --full-refresh
            dbt test --target bigquery

      - run:
          name: "Run Tests - Spark (criteria)"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target spark --full-refresh
            dbt run --target spark --full-refresh --vars 'ad_reporting__google_ads_type: criteria' -m stg_google_ads+
            dbt test --target spark
      - run:
          name: "Run Tests - Redshift (criteria)"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target redshift --full-refresh
            dbt run --target redshift --full-refresh --vars 'ad_reporting__google_ads_type: criteria' -m stg_google_ads+
            dbt test --target redshift
      - run:
          name: "Run Tests - Snowflake (criteria)"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target snowflake --full-refresh
            dbt run --target snowflake --full-refresh --vars 'ad_reporting__google_ads_type: criteria' -m stg_google_ads+
            dbt test --target snowflake
      - run:
          name: "Run Tests - BigQuery (criteria)"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/home/circleci/gcloud-service-key.json"

          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target bigquery --full-refresh
            dbt run --target bigquery --full-refresh --vars 'ad_reporting__google_ads_type: criteria' -m stg_google_ads+
            dbt test --target bigquery